
services:

  postgres:
    image: "postgres:17.5-alpine"
    container_name: AudioShare
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT_INNER}" 
    healthcheck:
      interval: 15s
      timeout: 5s
      retries: 5
    restart: unless-stopped   


