  
services:

  postgres:
    image: "postgres:17.5-alpine"
    container_name: ASPostgres
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DBNAME}
      - POSTGRES_USER=${POSTGRES_USER}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "${POSTGRES_PORT}:5432" 
    # healthcheck:
      # test: [ "CMD-SHELL", "pg_isready", "-d", "books_db" ]
      # interval: 10s
      # timeout: 7s
      # retries: 5
    restart: unless-stopped   
    networks:
      - AudioShare

  redis:
    image: "redis:7-alpine"
    container_name: ASRedis
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DB=${REDIS_DB}
    ports:
      - "${REDIS_PORT}:6379" 
    volumes:
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 7s
      retries: 5
    restart: unless-stopped   
    networks:
      - AudioShare

  minio:
    image: minio/minio
    container_name: ASObjectMinio
    command: server /data --console-address ":${MINIO_CONSOLE}"
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET}
    ports: 
      - "${MINIO_PORT}:9000" 
      - "${MINIO_CONSOLE}:9001" 
    volumes:
      - minio_data:/data
    restart: unless-stopped   
    networks:
      - AudioShare

  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: ASApp
    environment:
      - CONN_CONFIG_PATH=conn_config.env
      - DB_CONFIG_PATH=db_config.env
    ports:
      - "${HTTP_ADDRESS}:8080"
    depends_on:
      - postgres
      - redis
      - minio
    networks:
      - AudioShare
    restart: unless-stopped
  
networks:
  AudioShare:
    driver: bridge     

volumes:
  postgres_data:
  redis_data:
  minio_data: